### ISSUE TITLE
Include/exclude select field(s)

### ISSUE THREAD

**Issue by galantra** [thiswillbeyourgithub/HapaxPredator#1]
First, thank you for the add-on! Thoughtful name.

Second, a suggestion: posibility to select fields that the user wants to include or exclude. This is useful, for example, when you have swaths of textbook-style info in the Extra field.

**Comment by thiswillbeyourgithub** [comment]
Hi!

The fact that you appreciated the title of this addon really motivated me to implement this feature.

Thanks a lot for the suggestion :)

Implemented in febc721

I also cleaned up quite a few things and enhanced the code.
